version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot\mvcapp
hooks:
  BeforeInstall:
    - location: Scripts/Before-Install.ps1
      timeout: 300
  AfterInstall:
    - location: Scripts/After-Install.ps1
      timeout: 300
  ApplicationStart:
    - location: Scripts/Application-Start.ps1
      timeout: 300
  ApplicationStop:
    - location: Scripts/Application-Stop.ps1
      timeout: 300
