version: 0.0
os: windows
files:
  - source: app  
    destination: C:\inetpub\wwwroot\Coursework.Frontend

hooks:
  ApplicationStop:
    - location: scripts/Application-Stop.ps1
      timeout: 60
      runas: Administrator

  BeforeInstall:
    - location: scripts/Before-Install.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: scripts/SetPermissions.ps1
      timeout: 300
      runas: Administrator

  ApplicationStart:
    - location: scripts/Application-Start.ps1
      timeout: 60
      runas: Administrator